---
title: "Data 607 Final Project: Population Internet Access and Economic Growth"
authors: "Emily El Mouaquite, Long Lin, Pascal Hermann Kouogang Tafo, Ziaho Yu"
format: html
editor: visual
---

## Introduction

For this project, we want to investigate the relationship between internet access and economic opportunity through the following research question:

**Is higher internet access associated with stronger economic growth?**

To answer this question, we will integrate data from the online dataset [Share of the population using the Internet](https://ourworldindata.org/grapher/share-of-individuals-using-the-internet) (CSV file). Economic indicators, including GDP (USD) and GDP growth over time, will be retrieved through the [World Bank Indicators API](https://datahelpdesk.worldbank.org/knowledgebase/articles/889392-about-the-indicators-api-documentation), which provides JSON/XML data for all countries. Our motivation for doing this project is to see if, in a world where digital connectivity has become essential for education, commerce, and innovation, whether unequal access to the internet reinforces existing economic inequalities. By analyzing long‑term trends in internet usage alongside GDP growth, this project aims to quantify how strongly digital access correlates with national economic performance.

The workflow for this project will include: cleaning the internet access data from the CSV, and conducting statistical analyses to investigate the correlation between internet access and GDP growth over time. Possible hurdles that we might encounter could be misalignment between the CSV data and the data found in the API, missing data for some countries, and having to filter through the API data, which is very large.
